### PR TITLE
#104: Implementing support for ExtendedAttributes on a Link

### PR DESCRIPTION
**Pull request by mkamonster**

### CODE REVIEW

**Comment by mkamonster** [comment]
Is this what you have in mind? Or is this not in line for WebApi.Hal?

**Comment by wis3guy** [comment]
@mkamonster i wonder why you opted for using a dictionary to add *extended* properties to the link object. Moreover, i wonder why you would want to use that. The HAL spec states a finite set of allowed attributes, as can be read here: https://tools.ietf.org/html/draft-kelly-json-hal-06#section-5

```
5.  Link Objects  . . . . . . . . . . . . . . . . . . . . . . . .   4
     5.1.  href  . . . . . . . . . . . . . . . . . . . . . . . . . .   5
     5.2.  templated . . . . . . . . . . . . . . . . . . . . . . . .   5
     5.3.  type  . . . . . . . . . . . . . . . . . . . . . . . . . .   5
     5.4.  deprecation . . . . . . . . . . . . . . . . . . . . . . .   5
     5.5.  name  . . . . . . . . . . . . . . . . . . . . . . . . . .   5
     5.6.  profile . . . . . . . . . . . . . . . . . . . . . . . . .   6
     5.7.  title . . . . . . . . . . . . . . . . . . . . . . . . . .   6
     5.8.  hreflang  . . . . . . . . . . . . . . . . . . . . . . . .   6
```

If we were to add support for additional properties, i would suggest we only allow the properties stated in the spec, in order to avoid dialects. Only a specifically written client would know what to do with *custom* attributes. If we chose to go down that route, imho we should add specific properties, rather than a free-form dictionary.

**Comment by kbrichan** [comment]
In looking at issue #104 from @mkamonster, the motivation for extended link attributes apparently involves reconciling two disparate link standards, hal and atom.

We encountered the other day another motivation for extended link attributes, where we wanted to give the client a hint about HTTP verbs allowed on a particular instance of a resource (such as whether it is deletable) without having to do an OPTIONS request.

We opted to solve the problem in another way to avoid requiring clients to be aware of custom link attributes.

I agree with @wis3guy we probably shouldn't have custom attributes. How to solve the need for "length" I'm not sure, but it sounds like knowing the actual length is not as important as knowing whether the resource is really big. You might consider inventing a different rel meaning a huge enclosure -- probably not as ideal as being able to communicate the length, but at least it's within the standard.

**Comment by panmanphil** [comment]
While I'm 90% in agreement on not having extra link attributes, mostly because the link is not the part of a client would likely be looking to adjust. I do wonder about custom media formats that extend HAL. application/phil+hal+json can do whatever it wants right? 

The real answer is most likely in the base spirit of HAL that the additional semantics implied by a link should be described in the documentation for the relation, which can be enhanced by machine readable docs. I don't love this answer: it would be really awesome to have a link specify the http method for example GET/POST/PUT/DELETE/PATCH and so on.

**Comment by panmanphil** [comment]
Closing this is a general consensus was to not add these custom attributes as it breaks with the spec, while acknowledging that yes what this was trying to solve is worth solving somehow.

**Pull request closed without merging**
