### PR TITLE
Added support for resources that do not have any links

### PR DESCRIPTION
**Pull request by wis3guy**
Triggered by issue https://github.com/JakeGinnivan/WebApi.Hal/issues/98

### CODE REVIEW

**Comment by panmanphil** [comment]
looks reasonable to me, thanks for doing it.

**Comment by wis3guy** [comment]
@JakeGinnivan Will you do the merge and possibly update the nuget package?

**Comment by JMontagu** [comment]
@JakeGinnivan @wis3guy any time-frame on the nuget package update? Not critical, but this is a nice-to-have fix for the vnd.errors type :)

**Comment by wis3guy** [comment]
We have pushed a new version last week (version 2.6.0: https://www.nuget.org/packages/WebApi.Hal/)

**Pull request merged**
