### PR TITLE
Set Default content type header to application/json+hal

### PR DESCRIPTION
**Pull request by cfbarbero**
Adding support to JsonHalMediaTypeFormatter to force the response content-type to application/json+hal

### CODE REVIEW

**Comment by wis3guy** [comment]
@cfbarbero I agree with @panmanphil in that this is not behavior the formatter should enforce. My suggestion would be that you build your own binaries from your fork. If the request is for an `application/json` formatted resource than that is how the api ought to respond.

**Comment by cfbarbero** [comment]
Ok. Seems strange to me that you could get a response in json+hal format with application/json content-type, but I'll cancel this pull request since that seems to be the prevailing opinion.

**Comment by JakeGinnivan** [comment]
Correct me if I am wrong all, but if we request application/json then the formatter does not include hypermedia? Maybe we could put this behind a flag instead. `new JsonHalMediaTypeFormatter { Indent = true, EnforceMediaType = true }`?

Maybe we can enforce this then the the default json formatter would be used for application/json? Or does that not work due to our extra types/base classes?

**Comment by wis3guy** [comment]
Hmm, that sounds like a bug doesn't it? My concern is with the content type that is returned. Imho, if the client explicitly accepts `application/json` we should return our HAL serialised response, with that same content type. We should only return `application/hal+json` if the client states it is capable of dealing with it.

In the end, `application/hal+json` is just json, but we should not fight against standard conneg behavior, right?

**Comment by panmanphil** [comment]
I did a little more reading on what others are doing for this. Here is what i came up with. First non nonambiguous bits:
client passes Accept:application/json we return application/json
client passes Accept:application/hal+json we return application/hal+json

If you don't want to support a request for application/json or if you receive a request with Accept:foo+json you should return a 406 NOT ACCEPTABLE. You CAN return information telling the client what formats you do support. you CAN return a format you  do support instead. Honestly there seems to be no consensus way to handle this. 

So rereading the original pull request he only wants to support applciation/hal+json and he should be able to do so. I also agree this shouldn't be the default, most people would rather support both. It the client then breaks because they aren't using hypermedia and the api changes it is on them. So having a way to disable application/json would be good. I think it would also be good to be able to pass a 406 header if we don't support the requested content-type. 

3 cents worth!

**Pull request closed without merging**
